<?xml version="1.0" encoding="UTF-8"?>

<!-- File was generated by XSLfast 6.0, build 11/09/2012 -->
<!-- Layout version: 20 -->
<!-- Please leave unchanged; manage layouts instead -->
<!DOCTYPE xsl:stylesheet [
<!ENTITY XML "http://www.w3.org/TR/REC-xml">
<!ENTITY XMLNames "http://www.w3.org/TR/REC-xml-names">
<!ENTITY XSLT.ns "http://www.w3.org/1999/XSL/Transform">
<!ENTITY XSLTA.ns "http://www.w3.org/1999/XSL/TransformAlias">
<!ENTITY XSLFO.ns "http://www.w3.org/1999/XSL/Format">
<!ENTITY copy "&#169;">
<!ENTITY trade "&#8482;">
<!ENTITY deg "&#x00b0;">
<!ENTITY gt "&#62;">
<!ENTITY sup2 "&#x00b2;">
<!ENTITY frac14 "&#x00bc;">
<!ENTITY quot "&#34;">
<!ENTITY frac12 "&#x00bd;">
<!ENTITY euro "&#x20ac;">
<!ENTITY Omega "&#937;">
]>


<xsl:stylesheet 
	xmlns:xs="http://www.w3.org/2001/XMLSchema"
	xmlns:func="http://exslt.org/functions"
	xmlns:exslt="http://exslt.org/common"
	xmlns:fox="http://xmlgraphics.apache.org/fop/extensions"
	xmlns:saxon="http://saxon.sf.net/" extension-element-prefixes="saxon"
	xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
	xmlns:xslfast="http://www.xslfast.com"
	xmlns:common="http://exslt.org/common"
	xmlns:fo="http://www.w3.org/1999/XSL/Format" version="2.0"
	xmlns:msxsl="urn:schemas-microsoft-com:xslt"
	xmlns:NS1="http://www.greco.eu/schemas/2014/GOSPOS">


<xsl:variable name="path" select="document-uri(document(''))" />
<xsl:variable name="path1" select="base-uri()" />
<xsl:variable name="path2" select="static-base-uri()" />
<xsl:variable name="path3" select="replace(base-uri(),'(.*/)[^/]+?.xml','$1')" />

<xsl:variable name="xxslfile" select="codepoints-to-string(reverse(string-to-codepoints(substring-before(codepoints-to-string(reverse(string-to-codepoints($path))), '/'))))"/> <!-- file alleine -->
<xsl:variable name="xxbasedir" select="substring-before($path2,$xxslfile)" /> <!-- Verzeichnis, von dem aus das xsl file geladen wurde -->


<xsl:variable name="common_img" select="concat($xxbasedir,'IMG','/')" />
<xsl:variable name="special_img" select="concat($xxbasedir,'..','/','IMG','/')" />

<xsl:template match="NS1:form">
<fo:root xmlns:fo="http://www.w3.org/1999/XSL/Format">
<fo:layout-master-set>
<fo:simple-page-master master-name="masterNamePageMain0" page-height="845.0pt" page-width="598.0pt" margin-top="25.61pt" margin-left="31.0pt" margin-bottom="19.92pt" margin-right="31.0pt" reference-orientation="0" fox:bleed="0pt" fox:crop-box="media-box" fox:crop-offset="0pt" fox:scale="1.0">
<xsl:variable name="backgroundImageRepeat">no-repeat</xsl:variable><fo:region-body margin-left="40.12pt" margin-top="85.36pt" margin-bottom="68.29pt" margin-right="23.05pt"  background-position-horizontal="left" background-position-vertical="top" />
<fo:region-before extent="85.36pt" precedence="true"  background-position-horizontal="left" background-position-vertical="top" />
<fo:region-after extent="68.29pt" precedence="true"  background-position-horizontal="left" background-position-vertical="top" />
<fo:region-start extent="40.12pt"  background-position-horizontal="left" background-position-vertical="top" />
<fo:region-end extent="23.05pt"  background-position-horizontal="left" background-position-vertical="top" />
</fo:simple-page-master>
<fo:simple-page-master master-name="masterNamePageFirst1" page-height="845.0pt" page-width="598.0pt" margin-top="25.61pt" margin-left="31.01pt" margin-bottom="19.92pt" margin-right="31.01pt" reference-orientation="0" fox:bleed="0pt" fox:crop-box="media-box" fox:crop-offset="0pt" fox:scale="1.0">
<xsl:variable name="backgroundImageRepeat">no-repeat</xsl:variable><fo:region-body margin-left="40.12pt" margin-top="85.36pt" margin-bottom="68.29pt" margin-right="23.05pt"  background-position-horizontal="left" background-position-vertical="top" />
<fo:region-before region-name="regionBefore1" extent="85.36pt" precedence="true"  background-position-horizontal="left" background-position-vertical="top" />
<fo:region-after region-name="regionAfter1" extent="68.29pt" precedence="true"  background-position-horizontal="left" background-position-vertical="top" />
<fo:region-start region-name="regionStart1" extent="40.12pt"  background-position-horizontal="left" background-position-vertical="top" />
<fo:region-end region-name="regionEnd1" extent="23.05pt"  background-position-horizontal="left" background-position-vertical="top" />
</fo:simple-page-master>
<fo:simple-page-master master-name="masterNamePageRest2" page-height="845.0pt" page-width="598.0pt" margin-top="25.61pt" margin-left="31.01pt" margin-bottom="19.92pt" margin-right="31.01pt" reference-orientation="0" fox:bleed="0pt" fox:crop-box="media-box" fox:crop-offset="0pt" fox:scale="1.0">
<xsl:variable name="backgroundImageRepeat">no-repeat</xsl:variable><fo:region-body margin-left="40.12pt" margin-top="85.36pt" margin-bottom="68.29pt" margin-right="23.05pt"  background-position-horizontal="left" background-position-vertical="top" />
<fo:region-before region-name="regionBefore2" extent="85.36pt" precedence="true"  background-position-horizontal="left" background-position-vertical="top" />
<fo:region-after region-name="regionAfter2" extent="68.29pt" precedence="true"  background-position-horizontal="left" background-position-vertical="top" />
<fo:region-start region-name="regionStart2" extent="40.12pt"  background-position-horizontal="left" background-position-vertical="top" />
<fo:region-end region-name="regionEnd2" extent="23.05pt"  background-position-horizontal="left" background-position-vertical="top" />
</fo:simple-page-master>
<fo:page-sequence-master master-name="masterSequenceName1">
<fo:repeatable-page-master-alternatives>
<fo:conditional-page-master-reference master-reference="masterNamePageFirst1" page-position="first"/>
<fo:conditional-page-master-reference master-reference="masterNamePageRest2" page-position="rest"/>
</fo:repeatable-page-master-alternatives>
</fo:page-sequence-master>
</fo:layout-master-set>
<fo:bookmark-tree> </fo:bookmark-tree>
<fo:page-sequence master-reference="masterSequenceName1" format="1">
<xsl:attribute name="force-page-count">no-force</xsl:attribute>
<fo:static-content flow-name="regionBefore1">
<xsl:call-template name="templ_header"></xsl:call-template></fo:static-content>
<fo:static-content flow-name="regionAfter1">
<fo:block-container display-align="before" reference-orientation="0">
<fo:block position="relative" text-align="start" color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Arial" font-size="12.0pt" white-space-collapse="false"  linefeed-treatment="preserve" white-space-treatment="ignore-if-surrounding-linefeed"  hyphenate="true" language="en"  padding-bottom="0.0pt" start-indent="0.0pt" end-indent="0.0pt" padding-top="0.0pt" padding="0.0pt" width="100.0pt"  height="30.0pt" ><xsl:call-template name="templ_footer"></xsl:call-template></fo:block>
</fo:block-container>
</fo:static-content>
<fo:static-content flow-name="regionStart1">
<fo:block-container position="absolute" top="178.97000000000003pt" left="-19.910000000000004pt" width="31.94pt" height="20.56pt" >
 <fo:block  keep-together="auto" >
  <fo:instream-foreign-object>
   <svg:svg xmlns:svg="http://www.w3.org/2000/svg" width = "16.94pt" height="5.5600000000000005pt">
    <svg:g style="stroke:rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0);  fill: none; stroke-dasharray: none; stroke-opacity: 1; stroke-width:0.28pt">
     <svg:line  x1="0.28pt" y1="0.28pt" x2="11.66pt" y2="0.28pt" />
    </svg:g>
   </svg:svg>
  </fo:instream-foreign-object>
 </fo:block>
</fo:block-container>
<fo:block-container position="absolute" top="297.9pt" left="-19.910000000000004pt" width="31.94pt" height="20.56pt" >
 <fo:block  keep-together="auto" >
  <fo:instream-foreign-object>
   <svg:svg xmlns:svg="http://www.w3.org/2000/svg" width = "16.94pt" height="5.5600000000000005pt">
    <svg:g style="stroke:rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0);  fill: none; stroke-dasharray: none; stroke-opacity: 1; stroke-width:0.28pt">
     <svg:line  x1="0.28pt" y1="0.28pt" x2="11.66pt" y2="0.28pt" />
    </svg:g>
   </svg:svg>
  </fo:instream-foreign-object>
 </fo:block>
</fo:block-container>
</fo:static-content>
<fo:static-content flow-name="regionEnd1">
  <fo:block/>
</fo:static-content>
<fo:static-content flow-name="regionBefore2">
<fo:block-container display-align="before" reference-orientation="0">
<fo:block position="relative" text-align="start" color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Arial" font-size="12.0pt" white-space-collapse="false"  linefeed-treatment="preserve" white-space-treatment="ignore-if-surrounding-linefeed"  hyphenate="true" language="en"  padding-bottom="0.0pt" start-indent="0.0pt" end-indent="0.0pt" padding-top="0.0pt" padding="0.0pt" width="100.0pt"  height="30.0pt" ><xsl:call-template name="templ_header_logo_only"></xsl:call-template></fo:block>
</fo:block-container>
</fo:static-content>
<fo:static-content flow-name="regionAfter2">
<fo:block-container display-align="before" reference-orientation="0">
<fo:block position="relative" text-align="start" color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Arial" font-size="12.0pt" white-space-collapse="false"  linefeed-treatment="preserve" white-space-treatment="ignore-if-surrounding-linefeed"  hyphenate="true" language="en"  padding-bottom="0.0pt" start-indent="0.0pt" end-indent="0.0pt" padding-top="0.0pt" padding="0.0pt" width="100.0pt"  height="30.0pt" ><xsl:call-template name="templ_footer"></xsl:call-template></fo:block>
</fo:block-container>
</fo:static-content>
<fo:static-content flow-name="regionStart2">
  <fo:block/>
</fo:static-content>
<fo:static-content flow-name="regionEnd2">
  <fo:block/>
</fo:static-content>
<fo:flow flow-name="xsl-region-body">
<fo:block/>
<fo:block-container position="absolute" top="1.0300000000000011pt" left="7.880000000000003pt" height="30.0pt" width="100.0pt" display-align="before" reference-orientation="0" fox:transform="rotate(0) , translate(0, 0)">
<fo:block text-align="start" color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Arial" font-size="12.0pt" padding-bottom="0.0pt" start-indent="0.0pt" end-indent="0.0pt" padding-top="0.0pt" padding="0.0pt" position="relative" height="30.0pt" width="100.0pt" keep-together="auto"  line-height="14.5pt" white-space-collapse="false"  linefeed-treatment="preserve" white-space-treatment="ignore-if-surrounding-linefeed"  hyphenate="true" language="en" ><xsl:choose>
<xsl:when test="NS1:item[@NS1:name='production']">
<xsl:if test="NS1:item[@NS1:name='production']/@NS1:value!='BO1001'">
   <fo:block-container absolute-position="absolute" top="0.0pt" left="20.0cm"> 
	<fo:block span="none" text-align="right">
		<fo:external-graphic src="url({concat($common_img,'testdoc.jpg')})"/>
	</fo:block>
   </fo:block-container>
</xsl:if>
</xsl:when>

<xsl:otherwise>
<fo:block-container absolute-position="absolute" top="0.0pt" left="20.0cm"> 
	<fo:block span="none" text-align="right">
		<fo:external-graphic src="url({concat($common_img,'testdoc.jpg')})"/>
	</fo:block>
</fo:block-container>
</xsl:otherwise>
</xsl:choose></fo:block>
</fo:block-container>
<xsl:call-template name="templ_kopf"><xsl:with-param name="kopf_typ">null</xsl:with-param></xsl:call-template><fo:block-container position="absolute" top="89.02999999999999pt" left="16.880000000000003pt" height="29.0pt" width="450.0pt" display-align="before" reference-orientation="0" fox:transform="rotate(0) , translate(0, 0)">
<fo:block text-align="start" color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Arial" font-size="12.0pt" padding-bottom="0.0pt" start-indent="0.0pt" end-indent="0.0pt" padding-top="0.0pt" padding="0.0pt" position="relative" height="29.0pt" width="450.0pt" keep-together="auto"  white-space-collapse="false"  linefeed-treatment="preserve" white-space-treatment="ignore-if-surrounding-linefeed"  hyphenate="true" language="en" ><xsl:call-template name="check_invalid"></xsl:call-template></fo:block>
</fo:block-container>
<fo:block break-before="auto"/>
<fo:block-container  reference-orientation="0" >
<fo:block space-before="10.0pt" space-before.conditionality="retain" keep-together="auto" ><!-- GENERATE TABLE START-->

<fo:table table-layout="fixed" width="100%">
<fo:table-column column-width="469.0pt" />
<fo:table-body>
<xsl:for-each select=".">

    <fo:table-row>
<fo:table-cell padding-bottom="0.0pt" start-indent="0.0pt" end-indent="0.0pt" padding-top="0.0pt" padding="0.0pt" display-align="before" width="469.0pt"  reference-orientation="0">
<fo:block-container display-align="before" reference-orientation="0">
<fo:block position="relative" text-align="start" color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="11.0pt" font-weight="bold" white-space-collapse="false"  linefeed-treatment="preserve" white-space-treatment="ignore-if-surrounding-linefeed"  hyphenate="false" language="en"  padding-bottom="0.0pt" start-indent="0.0pt" end-indent="0.0pt" padding-top="0.0pt" padding="0.0pt"><xsl:value-of select="concat('Informativna ponuda / ','Broj ponude leasinga ',NS1:item[@NS1:name='leasing_subject']/@NS1:value)"/></fo:block>
</fo:block-container>
</fo:table-cell>

    </fo:table-row>

    <fo:table-row>
<fo:table-cell padding-bottom="0.0pt" start-indent="0.0pt" end-indent="0.0pt" padding-top="0.0pt" padding="0.0pt" display-align="before" width="469.0pt"  reference-orientation="0">
<fo:block-container display-align="before" reference-orientation="0">
<fo:block position="relative" text-align="start" color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="11.0pt" white-space-collapse="false"  linefeed-treatment="preserve" white-space-treatment="ignore-if-surrounding-linefeed"  hyphenate="false" language="en"  padding-bottom="0.0pt" start-indent="0.0pt" end-indent="0.0pt" padding-top="15.65pt"><xsl:text>Poštovani,</xsl:text></fo:block>
</fo:block-container>
</fo:table-cell>

    </fo:table-row>

    <fo:table-row>
<fo:table-cell padding-bottom="0.0pt" start-indent="0.0pt" end-indent="0.0pt" padding-top="0.0pt" padding="0.0pt" display-align="before" width="469.0pt"  reference-orientation="0">
<fo:block break-before="auto"/>
<fo:block-container font-stretch="normal" text-transform="none">
<fo:block linefeed-treatment="preserve" white-space-treatment="ignore-if-surrounding-linefeed"  padding-bottom="0.0pt" start-indent="0.0pt" end-indent="0.0pt" padding-top="0.0pt" padding="0.0pt" line-height="14.5pt" white-space-collapse="false"  hyphenate="true" language="en"  text-align="start" keep-together="auto"  letter-spacing="normal" word-spacing="normal" font-stretch="normal" text-transform="none">
<fo:block text-align="left" white-space-collapse="false"  hyphenate="true" language="en"  linefeed-treatment="preserve" white-space-treatment="ignore-if-surrounding-linefeed" >
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="11.0pt">
<xsl:text>Društvo </xsl:text></fo:inline>
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="11.0pt" font-weight="bold">
<xsl:text>GrECo JLT Croatia d.o.o.</xsl:text></fo:inline>
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="11.0pt">
<xsl:text> je ovlašteni posrednik za poslove osiguranja cjelokupne </xsl:text></fo:inline>
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="11.0pt" font-weight="bold">
<xsl:text>ERSTE Grupe</xsl:text></fo:inline>
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="11.0pt">
<xsl:text>, a u skladu s time nastavljamo dugogodišnu suradnju s ovlaštenim partnerom</xsl:text></fo:inline>
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="11.0pt" font-weight="bold">
<xsl:text> Erste &amp; Steiermärkische S-Leasing d.o.o. </xsl:text></fo:inline>
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="11.0pt">
<xsl:text>Slobodni smo Vam ponuditi ugovaranje Vaših polica osiguranja za objekte leasinga po najpovoljnijim uvjetima.</xsl:text></fo:inline>
</fo:block>
<fo:block text-align="left" white-space-collapse="false"  hyphenate="true" language="en"  linefeed-treatment="preserve" white-space-treatment="ignore-if-surrounding-linefeed" >
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="11.0pt">
</fo:inline>
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="11.0pt">
<xsl:text>U nastavku Vam dostavljamo informativne ponude za ugovaranje polica osiguranja automobilskog kaska sa dva renominirana osiguratelja na tržištu. </xsl:text></fo:inline>
</fo:block>
<fo:block text-align="left" white-space-collapse="false"  hyphenate="true" language="en"  linefeed-treatment="preserve" white-space-treatment="ignore-if-surrounding-linefeed" >
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="11.0pt">
</fo:inline>
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="11.0pt">
<xsl:text>Ukoliko se odlučite za neku od dolje navedenih opcija, ljubazno Vas molimo da potpišete niže navedenu</xsl:text></fo:inline>
</fo:block>
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="11.0pt">
<xsl:text>punomoć te nam istu dostavite na navedene kontakt podatke u zaglavlju.</xsl:text></fo:inline>
<fo:block text-align="left" white-space-collapse="false"  hyphenate="true" language="en"  linefeed-treatment="preserve" white-space-treatment="ignore-if-surrounding-linefeed" >
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="11.0pt">
<xsl:text>
</xsl:text></fo:inline>
</fo:block>
</fo:block>
</fo:block-container>
<fo:block break-after="auto"/>
</fo:table-cell>

    </fo:table-row>

    <fo:table-row>
<fo:table-cell padding-bottom="0.0pt" start-indent="0.0pt" end-indent="0.0pt" padding-top="0.0pt" padding="0.0pt" display-align="before" width="469.0pt"  reference-orientation="0">
<fo:block-container display-align="before" reference-orientation="0">
<fo:block position="relative" text-align="start" color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="11.0pt" white-space-collapse="false"  linefeed-treatment="preserve" white-space-treatment="ignore-if-surrounding-linefeed"  hyphenate="true" language="en"  padding-bottom="0.0pt" start-indent="0.0pt" end-indent="0.0pt" padding-top="0.0pt" padding="0.0pt">
<fo:block font-size="12pt" font-family="Calibri" font-weight="bold">ODABRANA OPCIJA (označiti za X)</fo:block> <!-- das wäre eine Überschrift -->
    <fo:block font-size="12pt" space-after="3pt" text-indent="8pt" padding-top="8pt">
        <fo:table border="solid" border-collapse="collapse" > <!-- hier wird eine Umrandung gesetzt -->
        	<fo:table-column column-width="50%"/>
        	<fo:table-column column-width="50%"/>

            <fo:table-body font-size="12pt">

		<fo:table-row height="12pt">  <!-- das wäre der Table-Body also der eigentliche Content der Tabelle  -->
                    <fo:table-cell>
                    	<fo:block>[_] Uniqa osiguranje d.d.</fo:block>
		    </fo:table-cell>
                    <fo:table-cell>
                        <fo:block> PREMIJA: <xsl:value-of select="concat(NS1:item[@NS1:name='premium_uniqa_string']/@NS1:value,' ',NS1:item[@NS1:name='currency']/@NS1:value)" /> </fo:block>
		    </fo:table-cell>
                </fo:table-row>
                
		<fo:table-row height="12pt">  <!-- das wäre der Table-Body also der eigentliche Content der Tabelle  -->
                    <fo:table-cell>
                    	<fo:block>[_] Wiener osiguranje d.d.</fo:block>
		    </fo:table-cell>
                    <fo:table-cell>
                        <fo:block> PREMIJA: <xsl:value-of select="concat(NS1:item[@NS1:name='premium_wstv_string']/@NS1:value,' ',NS1:item[@NS1:name='currency']/@NS1:value)" /> </fo:block>
		    </fo:table-cell>
                </fo:table-row>
             
             </fo:table-body>

        </fo:table>
    </fo:block>


<fo:block font-size="8pt" font-family="Calibri">

<xsl:variable name="listprice">
<xsl:text>OSNOVICA ZA IZRAČUN PREMIJE: </xsl:text>
<xsl:value-of select="concat(NS1:item[@NS1:name='finance_amount_string']/@NS1:value,' ',NS1:item[@NS1:name='currency']/@NS1:value)" />
</xsl:variable>
<!--<xsl:value-of select="$listprice" /> -->

<xsl:variable name="leasingtyp">
<xsl:text>VRSTA LEASINGA: </xsl:text>
<xsl:choose>
<xsl:when test="NS1:item[@NS1:name='finance_type']/@NS1:value='OL'" >
	<xsl:text>OPERATIVNI LEASING </xsl:text>
</xsl:when>
<xsl:when test="NS1:item[@NS1:name='finance_type']/@NS1:value='FL'" >
	<xsl:text>FINANCIJSKI LEASING </xsl:text>
</xsl:when>
<xsl:otherwise> 
<xsl:text>NO DATA ENTRY</xsl:text>
</xsl:otherwise>

</xsl:choose>
</xsl:variable>
<!--<xsl:value-of select="$leasingtyp" /> -->

<xsl:variable name="newcar">
<xsl:text>NOVO VOZILO: </xsl:text>
<xsl:choose>
<xsl:when test="NS1:item[@NS1:name='new_car']/@NS1:value='Yes'" >
	<xsl:text>Da </xsl:text>
</xsl:when>
<xsl:when test="NS1:item[@NS1:name='new_car']/@NS1:value='No'" >
	<xsl:text>Ne </xsl:text>
</xsl:when>
<xsl:otherwise> 
<xsl:text>NO DATA ENTRY</xsl:text>
</xsl:otherwise>
</xsl:choose>
</xsl:variable>
<!--<xsl:value-of select="$newcar" /> -->

<xsl:variable name="clause">
<xsl:text>Ukoliko je premija izražena u EUR ista će se preračunati u kn po srednjem tečaju HNB-a </xsl:text>
</xsl:variable>
<!--<xsl:value-of select="$clause" /> -->


<xsl:value-of select="concat($listprice,' | ',$leasingtyp,' | ', $newcar, ' | ',$clause)" />
</fo:block>
</fo:block>
</fo:block-container>
</fo:table-cell>

    </fo:table-row>

    <fo:table-row>
<fo:table-cell padding-bottom="0.0pt" start-indent="0.0pt" end-indent="0.0pt" padding-top="0.0pt" padding="0.0pt" display-align="before" width="469.0pt"  reference-orientation="0">
<fo:block break-before="auto"/>
<fo:block-container font-stretch="normal" text-transform="none">
<fo:block linefeed-treatment="preserve" white-space-treatment="ignore-if-surrounding-linefeed"  padding-bottom="0.0pt" start-indent="0.0pt" end-indent="0.0pt" padding-top="14.23pt" line-height="14.5pt" white-space-collapse="false"  hyphenate="true" language="en"  text-align="start" keep-together="auto"  letter-spacing="normal" word-spacing="normal" font-stretch="normal" text-transform="none">
<fo:block text-align="left" white-space-collapse="false"  hyphenate="true" language="en"  linefeed-treatment="preserve" white-space-treatment="ignore-if-surrounding-linefeed" >
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="9.0pt">
<xsl:text>Ova informativna ponuda izdana je od strane društva GrECo JLT Croatia d.o.o. te je društvo Erste &amp; Steiermärkische S-Leasing d.o.o. sukladno ugovoru o poslovnoj suradnji uručuje primatelju leasinga.</xsl:text></fo:inline>
</fo:block>
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="9.0pt" font-weight="bold">
<xsl:text>Ova je ponuda informativnog karaktera i kao takva podložna promjenama.</xsl:text></fo:inline>
</fo:block>
</fo:block-container>
<fo:block break-after="auto"/>
</fo:table-cell>

    </fo:table-row>

    <fo:table-row>
<fo:table-cell padding-bottom="0.0pt" start-indent="0.0pt" end-indent="0.0pt" padding-top="0.0pt" padding="0.0pt" display-align="before" width="469.0pt"  reference-orientation="0">
<fo:block-container display-align="before" reference-orientation="0">
<fo:block position="relative" text-align="start" color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="11.0pt" white-space-collapse="false"  linefeed-treatment="preserve" white-space-treatment="ignore-if-surrounding-linefeed"  hyphenate="true" language="en"  padding-bottom="0.0pt" start-indent="0.0pt" end-indent="0.0pt" padding-top="14.23pt" page-break-after="always"><xsl:call-template name="table_fuss_freitext"></xsl:call-template></fo:block>
</fo:block-container>
</fo:table-cell>

    </fo:table-row>

    <fo:table-row>
<fo:table-cell padding-bottom="0.0pt" start-indent="0.0pt" end-indent="0.0pt" padding-top="0.0pt" padding="0.0pt" display-align="before" width="469.0pt"  reference-orientation="0">
<fo:block break-before="auto"/>
<fo:block-container font-stretch="normal" text-transform="none">
<fo:block linefeed-treatment="preserve" white-space-treatment="ignore-if-surrounding-linefeed"  padding-bottom="0.0pt" start-indent="0.0pt" end-indent="0.0pt" padding-top="28.45pt" line-height="14.5pt" white-space-collapse="false"  hyphenate="true" language="en"  page-break-inside="avoid" page-break-after="always" text-align="start" keep-together="auto"  letter-spacing="normal" word-spacing="normal" font-stretch="normal" text-transform="none">
<fo:block text-align="center" white-space-collapse="false"  hyphenate="true" language="en"  linefeed-treatment="preserve" white-space-treatment="ignore-if-surrounding-linefeed" >
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="11.0pt" font-weight="bold">
<xsl:text>Ovlaštenje za posredovanje u osiguranju </xsl:text></fo:inline>
</fo:block>
<fo:block text-align="center" white-space-collapse="false"  hyphenate="true" language="en"  linefeed-treatment="preserve" white-space-treatment="ignore-if-surrounding-linefeed" >
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="11.0pt" font-weight="bold">
</fo:inline>
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="11.0pt" font-weight="bold">
<xsl:text>za objekte leasinga financirane od strane  Erste &amp; Steiermärkische S-Leasing d.o.o.</xsl:text></fo:inline>
</fo:block>
<fo:block text-align="center" white-space-collapse="false"  hyphenate="true" language="en"  linefeed-treatment="preserve" white-space-treatment="ignore-if-surrounding-linefeed" >
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="11.0pt" font-weight="bold">
<xsl:text>
</xsl:text></fo:inline>
</fo:block>
<fo:block text-align="center" white-space-collapse="false"  hyphenate="true" language="en"  linefeed-treatment="preserve" white-space-treatment="ignore-if-surrounding-linefeed" >
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="11.0pt" font-weight="bold">
<xsl:text>
</xsl:text></fo:inline>
</fo:block>
<fo:block text-align="center" white-space-collapse="false"  hyphenate="true" language="en"  linefeed-treatment="preserve" white-space-treatment="ignore-if-surrounding-linefeed" >
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="11.0pt" font-weight="bold">
<xsl:text>
</xsl:text></fo:inline>
</fo:block>
<fo:block text-align="center" white-space-collapse="false"  hyphenate="true" language="en"  linefeed-treatment="preserve" white-space-treatment="ignore-if-surrounding-linefeed" >
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="11.0pt" font-weight="bold">
<xsl:text>
</xsl:text></fo:inline>
</fo:block>
<fo:block text-align="center" white-space-collapse="false"  hyphenate="true" language="en"  linefeed-treatment="preserve" white-space-treatment="ignore-if-surrounding-linefeed" >
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="11.0pt" font-weight="bold">
</fo:inline>
</fo:block>
<fo:block text-align="right" white-space-collapse="false"  hyphenate="true" language="en"  linefeed-treatment="preserve" white-space-treatment="ignore-if-surrounding-linefeed" >
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="11.0pt">
<xsl:text>Mjesto i datum: ______________</xsl:text></fo:inline>
</fo:block>
<fo:block text-align="center" white-space-collapse="false"  hyphenate="true" language="en"  linefeed-treatment="preserve" white-space-treatment="ignore-if-surrounding-linefeed" >
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="11.0pt">
<xsl:text>
</xsl:text></fo:inline>
</fo:block>
<fo:block text-align="center" white-space-collapse="false"  hyphenate="true" language="en"  linefeed-treatment="preserve" white-space-treatment="ignore-if-surrounding-linefeed" >
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="11.0pt">
<xsl:text>
</xsl:text></fo:inline>
</fo:block>
<fo:block text-align="center" white-space-collapse="false"  hyphenate="true" language="en"  linefeed-treatment="preserve" white-space-treatment="ignore-if-surrounding-linefeed" >
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="11.0pt">
<xsl:text>
</xsl:text></fo:inline>
</fo:block>
<fo:block text-align="center" white-space-collapse="false"  hyphenate="true" language="en"  linefeed-treatment="preserve" white-space-treatment="ignore-if-surrounding-linefeed" >
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="11.0pt">
<xsl:text>
</xsl:text></fo:inline>
</fo:block>
<fo:block text-align="center" white-space-collapse="false"  hyphenate="true" language="en"  linefeed-treatment="preserve" white-space-treatment="ignore-if-surrounding-linefeed" >
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="11.0pt">
</fo:inline>
</fo:block>
<fo:block text-align="left" white-space-collapse="false"  hyphenate="true" language="en"  linefeed-treatment="preserve" white-space-treatment="ignore-if-surrounding-linefeed" >
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="11.0pt">
<xsl:text>kojim ovlašćujemo trgovačko društvo GrECo JLT Croatia d.o.o. za posredovanje u osiguranju, Zelinska 3, Zagreb, OIB 38928475156, da u naše ime i za naš račun provodi djelatnost pokretanja, predlaganja ili obavljanja poslova pripreme za sklapanje ugovora o osiguranju, pomoć pri izvršavanju prava iz ugovora o osiguranju, a posebno pri rješavanju odštetnih zahtjeva, naslovljenih na društvo za osiguranje, za objekte leasinga financirane od strane Erste &amp; Steiermärkische S-Leasing d.o.o. za vrijeme cijelog trajanja ugovora o leasingu.</xsl:text></fo:inline>
</fo:block>
<fo:block text-align="left" white-space-collapse="false"  hyphenate="true" language="en"  linefeed-treatment="preserve" white-space-treatment="ignore-if-surrounding-linefeed" >
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="11.0pt">
<xsl:text>
</xsl:text></fo:inline>
</fo:block>
<fo:block text-align="left" white-space-collapse="false"  hyphenate="true" language="en"  linefeed-treatment="preserve" white-space-treatment="ignore-if-surrounding-linefeed" >
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="11.0pt">
</fo:inline>
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="11.0pt">
<xsl:text>Za obavljanje usluga po ovom Ovlaštenju, a sukladno Zakonu o osiguranju, GrECo JLT Croatia d.o.o. neće potpisniku ovog Ovlaštenja naplatiti nikakvu proviziju niti drugu novčanu ili bilo kakvu drugu naknadu za izvršenu uslugu posredovanja u osiguranju, a koja je regulirana ugovorima s osiguravajućim društvima.</xsl:text></fo:inline>
</fo:block>
<fo:block text-align="left" white-space-collapse="false"  hyphenate="true" language="en"  linefeed-treatment="preserve" white-space-treatment="ignore-if-surrounding-linefeed" >
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="11.0pt">
<xsl:text>
</xsl:text></fo:inline>
</fo:block>
<fo:block text-align="left" white-space-collapse="false"  hyphenate="true" language="en"  linefeed-treatment="preserve" white-space-treatment="ignore-if-surrounding-linefeed" >
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="11.0pt">
</fo:inline>
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="11.0pt">
<xsl:text>Ovo Ovlaštenje ima važenje do opoziva i može se opozvati samo temeljem pisane obavijesti uz otkazni rok od mjesec dana. U slučaju opoziva ovog Ovlaštenja, GrECo JLT Croatia d.o.o. ima pravo i obvezu završiti sve radnje koje su započete temeljem ovog Ovlaštenja i koje su u vezi sa sklopljenim ugovorima o osiguranju.</xsl:text></fo:inline>
</fo:block>
<fo:block text-align="left" white-space-collapse="false"  hyphenate="true" language="en"  linefeed-treatment="preserve" white-space-treatment="ignore-if-surrounding-linefeed" >
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="11.0pt">
<xsl:text>
</xsl:text></fo:inline>
</fo:block>
<fo:block text-align="left" white-space-collapse="false"  hyphenate="true" language="en"  linefeed-treatment="preserve" white-space-treatment="ignore-if-surrounding-linefeed" >
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="11.0pt">
<xsl:text>
</xsl:text></fo:inline>
</fo:block>
<fo:block text-align="left" white-space-collapse="false"  hyphenate="true" language="en"  linefeed-treatment="preserve" white-space-treatment="ignore-if-surrounding-linefeed" >
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="11.0pt">
<xsl:text>
</xsl:text></fo:inline>
</fo:block>
<fo:block text-align="left" white-space-collapse="false"  hyphenate="true" language="en"  linefeed-treatment="preserve" white-space-treatment="ignore-if-surrounding-linefeed" >
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="11.0pt">
</fo:inline>
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="11.0pt" font-weight="bold">
<xsl:text>Davatelj Ovlaštenja</xsl:text></fo:inline>
</fo:block>
<fo:block text-align="left" white-space-collapse="false"  hyphenate="true" language="en"  linefeed-treatment="preserve" white-space-treatment="ignore-if-surrounding-linefeed" >
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="11.0pt" font-weight="bold">
<xsl:text>
</xsl:text></fo:inline>
</fo:block>
<fo:block text-align="left" white-space-collapse="false"  hyphenate="true" language="en"  linefeed-treatment="preserve" white-space-treatment="ignore-if-surrounding-linefeed" >
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="11.0pt" font-weight="bold">
<xsl:text>
</xsl:text></fo:inline>
</fo:block>
<fo:block text-align="left" white-space-collapse="false"  hyphenate="true" language="en"  linefeed-treatment="preserve" white-space-treatment="ignore-if-surrounding-linefeed" >
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="11.0pt" font-weight="bold">
</fo:inline>
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="11.0pt">
<xsl:text>Ime i prezime/Naziv:       _______________________________</xsl:text></fo:inline>
</fo:block>
<fo:block text-align="left" white-space-collapse="false"  hyphenate="true" language="en"  linefeed-treatment="preserve" white-space-treatment="ignore-if-surrounding-linefeed" >
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="11.0pt">
<xsl:text>
</xsl:text></fo:inline>
</fo:block>
<fo:block text-align="left" white-space-collapse="false"  hyphenate="true" language="en"  linefeed-treatment="preserve" white-space-treatment="ignore-if-surrounding-linefeed" >
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="11.0pt">
</fo:inline>
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="11.0pt">
<xsl:text>Adresa:                              _______________________________</xsl:text></fo:inline>
</fo:block>
<fo:block text-align="left" white-space-collapse="false"  hyphenate="true" language="en"  linefeed-treatment="preserve" white-space-treatment="ignore-if-surrounding-linefeed" >
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="11.0pt">
<xsl:text>
</xsl:text></fo:inline>
</fo:block>
<fo:block text-align="left" white-space-collapse="false"  hyphenate="true" language="en"  linefeed-treatment="preserve" white-space-treatment="ignore-if-surrounding-linefeed" >
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="11.0pt">
</fo:inline>
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="11.0pt">
<xsl:text>OIB:                                    _______________________________</xsl:text></fo:inline>
</fo:block>
<fo:block text-align="left" white-space-collapse="false"  hyphenate="true" language="en"  linefeed-treatment="preserve" white-space-treatment="ignore-if-surrounding-linefeed" >
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="11.0pt">
<xsl:text>
</xsl:text></fo:inline>
</fo:block>
<fo:block text-align="left" white-space-collapse="false"  hyphenate="true" language="en"  linefeed-treatment="preserve" white-space-treatment="ignore-if-surrounding-linefeed" >
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="11.0pt">
</fo:inline>
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="11.0pt">
<xsl:text>Potpis i pečat:                  _______________________________                                 MP</xsl:text></fo:inline>
</fo:block>
</fo:block>
</fo:block-container>
<fo:block break-after="auto"/>
</fo:table-cell>

    </fo:table-row>
</xsl:for-each></fo:table-body>
</fo:table>
</fo:block></fo:block-container>
<fo:block break-after="auto"/>
<fo:block break-before="auto"/>
<fo:block-container height="30.0pt" width="469.0pt" font-stretch="normal" text-transform="none">
<fo:block linefeed-treatment="preserve" white-space-treatment="ignore-if-surrounding-linefeed"  padding-bottom="0.0pt" start-indent="0.0pt" end-indent="0.0pt" padding-top="28.45pt" line-height="11.38pt" white-space-collapse="false"  hyphenate="true" language="en"  page-break-inside="avoid" text-align="justify" width="469.0pt"  height="30.0pt"  keep-together="auto"  letter-spacing="normal" font-stretch="normal" text-transform="none">
<fo:block text-align="justify" white-space-collapse="false"  hyphenate="true" language="en"  linefeed-treatment="preserve" white-space-treatment="ignore-if-surrounding-linefeed" >
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="8.0pt" font-weight="bold">
<xsl:text>Informacije sukladno obvezama posrednika u osiguranju i reosiguranju (ZOS čl. 424)</xsl:text></fo:inline>
</fo:block>
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="8.0pt">
<xsl:text>Slijedom Zakona o osiguranju (NN 30/15), obavezni smo Vas informirati, kako slijedi:</xsl:text></fo:inline>
<fo:block text-align="justify" white-space-collapse="false"  hyphenate="true" language="en"  linefeed-treatment="preserve" white-space-treatment="ignore-if-surrounding-linefeed" >
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="8.0pt">
<xsl:text>
</xsl:text></fo:inline>
</fo:block>
<fo:block text-align="justify" white-space-collapse="false"  hyphenate="true" language="en"  linefeed-treatment="preserve" white-space-treatment="ignore-if-surrounding-linefeed" >
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="8.0pt">
</fo:inline>
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="8.0pt">
<xsl:text>Ime i prezime te adresa osoba u društvu ovlaštenih za posredovanje u osiguranju i reosiguranju upisanih u Registar</xsl:text></fo:inline>
</fo:block>
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="8.0pt">
<xsl:text>posrednika u osiguranju i reosiguranju:</xsl:text></fo:inline>
<fo:block text-align="justify" white-space-collapse="false"  hyphenate="true" language="en"  linefeed-treatment="preserve" white-space-treatment="ignore-if-surrounding-linefeed" >
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="8.0pt">
</fo:inline>
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="8.0pt">
<xsl:text>1. Robert Fućak, Klenovica, Gaj 4, 51 250 Novi Vinodolski, ovlaštenje broj: PO 261 </xsl:text></fo:inline>
</fo:block>
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="8.0pt">
<xsl:text>2. Anita Hukman Savić, Hrastelnica 14c, 44 000 Sisak, ovlaštenje broj: PO 181</xsl:text></fo:inline>
<fo:block text-align="justify" white-space-collapse="false"  hyphenate="true" language="en"  linefeed-treatment="preserve" white-space-treatment="ignore-if-surrounding-linefeed" >
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="8.0pt">
</fo:inline>
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="8.0pt">
<xsl:text>3. Ivana Fratrić, J. Huttlera 27, 31 000 Osijek, ovlaštenje broj: PO 399</xsl:text></fo:inline>
</fo:block>
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="8.0pt">
<xsl:text>4. Mario Tikvić, Franje Miličevića 47, 10 000 Zagreb, ovlaštenje broj: PO 365</xsl:text></fo:inline>
<fo:block text-align="justify" white-space-collapse="false"  hyphenate="true" language="en"  linefeed-treatment="preserve" white-space-treatment="ignore-if-surrounding-linefeed" >
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="8.0pt">
</fo:inline>
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="8.0pt">
<xsl:text>5. Igor Turk, Mavrinci 112, 51 219 Čavle, ovlaštenje broj: PO 280</xsl:text></fo:inline>
</fo:block>
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="8.0pt">
<xsl:text>6. Ivana Šola, Srešov klanac 42, 10090 Zagreb, ovlaštenje broj: PO 380</xsl:text></fo:inline>
<fo:block text-align="justify" white-space-collapse="false"  hyphenate="true" language="en"  linefeed-treatment="preserve" white-space-treatment="ignore-if-surrounding-linefeed" >
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="8.0pt">
</fo:inline>
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="8.0pt">
<xsl:text>7. Dubravka Šumiga, Vukovarska cesta 126c, 31 000 Osijek, ovlaštenje broj: PO 382</xsl:text></fo:inline>
</fo:block>
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="8.0pt">
<xsl:text>8. Dinko Glavač, Naselje Vukšinec 75A, Donja Stubica, ovlaštenje broj: PO 405</xsl:text></fo:inline>
<fo:block text-align="justify" white-space-collapse="false"  hyphenate="true" language="en"  linefeed-treatment="preserve" white-space-treatment="ignore-if-surrounding-linefeed" >
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="8.0pt">
</fo:inline>
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="8.0pt">
<xsl:text>9. Bojan Baretić, Brajšina 11, Rijeka, ovlaštenje broj: PO 411</xsl:text></fo:inline>
</fo:block>
<fo:block text-align="justify" white-space-collapse="false"  hyphenate="true" language="en"  linefeed-treatment="preserve" white-space-treatment="ignore-if-surrounding-linefeed" >
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="8.0pt">
<xsl:text>
</xsl:text></fo:inline>
</fo:block>
<fo:block text-align="justify" white-space-collapse="false"  hyphenate="true" language="en"  linefeed-treatment="preserve" white-space-treatment="ignore-if-surrounding-linefeed" >
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="8.0pt">
</fo:inline>
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="8.0pt">
<xsl:text>Registar u kojem je posrednik, fizička osoba prijavljena i način provjere: Hrvatska agencija za nadzor financijskih usluga (HANFA), Miramarska 24b, Zagreb - pisanim upitom i /ili na</xsl:text></fo:inline>
<fo:inline color="rgb-icc(0,90,161, #CMYK, 1.0,0.44,0.0,0.37)" font-family="Calibri" font-size="8.0pt">
<xsl:text> www.hanfa.hr</xsl:text></fo:inline>
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="8.0pt">
<xsl:text>.</xsl:text></fo:inline>
</fo:block>
<fo:block text-align="justify" white-space-collapse="false"  hyphenate="true" language="en"  linefeed-treatment="preserve" white-space-treatment="ignore-if-surrounding-linefeed" >
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="8.0pt">
<xsl:text>
</xsl:text></fo:inline>
</fo:block>
<fo:block text-align="justify" white-space-collapse="false"  hyphenate="true" language="en"  linefeed-treatment="preserve" white-space-treatment="ignore-if-surrounding-linefeed" >
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="8.0pt">
</fo:inline>
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="8.0pt">
<xsl:text>Društvo za posredovanje u kojem je posrednik, fizička osoba zaposlen: GrECo JLT Croatia d.o.o. za posredovanje u osiguranju, Zelinska 3, Zagreb, OIB 38928475156 - rješenjem od 11.01.2007. g. Klasa UP/I-453-06/06-03/18, ur.broj 326-112-07-4 Hrvatska agencija za nadzor financijskih usluga (HANFA) je Društvu izdala dozvolu/ovlaštenje za obavljanje djelatnosti posredovanja u osiguranju i reosiguranju.</xsl:text></fo:inline>
</fo:block>
<fo:block text-align="justify" white-space-collapse="false"  hyphenate="true" language="en"  linefeed-treatment="preserve" white-space-treatment="ignore-if-surrounding-linefeed" >
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="8.0pt">
<xsl:text>
</xsl:text></fo:inline>
</fo:block>
<fo:block text-align="justify" white-space-collapse="false"  hyphenate="true" language="en"  linefeed-treatment="preserve" white-space-treatment="ignore-if-surrounding-linefeed" >
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="8.0pt">
</fo:inline>
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="8.0pt">
<xsl:text>Posrednik GrECo JLT Croatia d.o.o. za posredovanje u osiguranju ne posjeduje nikakav udjel u bilo kojem društvu za osiguranje na temelju kojih sudjeluje u pravu glasa odnosno kapitalu društva za osiguranje. </xsl:text></fo:inline>
</fo:block>
<fo:block text-align="justify" white-space-collapse="false"  hyphenate="true" language="en"  linefeed-treatment="preserve" white-space-treatment="ignore-if-surrounding-linefeed" >
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="8.0pt">
<xsl:text>
</xsl:text></fo:inline>
</fo:block>
<fo:block text-align="justify" white-space-collapse="false"  hyphenate="true" language="en"  linefeed-treatment="preserve" white-space-treatment="ignore-if-surrounding-linefeed" >
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="8.0pt">
</fo:inline>
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="8.0pt">
<xsl:text>Posrednik GrECo JLT Croatia d.o.o. za posredovanje u osiguranju ima sklopljene ugovore sa slijedećim osigurateljima: Allianz Zagreb d.d., Croatia osiguranje d.d., Croatia zdravstveno osiguranje d.d., Euroherc osiguranje d.d., Generali osiguranje d.d., Grawe Hrvatska d.d., HOK Osiguranje d. d., Izvor osiguranje d.d., Jadransko osiguranje d.d., Wiener osiguranje Vienna Insurance Group d.d., Merkur osiguranje d.d., Sunce osiguranje d.d., Triglav osiguranje d.d., Uniqa osiguranje d.d., Sava osiguranje d.d. </xsl:text></fo:inline>
</fo:block>
<fo:block text-align="justify" white-space-collapse="false"  hyphenate="true" language="en"  linefeed-treatment="preserve" white-space-treatment="ignore-if-surrounding-linefeed" >
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="8.0pt">
<xsl:text>
</xsl:text></fo:inline>
</fo:block>
<fo:block text-align="justify" white-space-collapse="false"  hyphenate="true" language="en"  linefeed-treatment="preserve" white-space-treatment="ignore-if-surrounding-linefeed" >
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="8.0pt">
</fo:inline>
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="8.0pt">
<xsl:text>Društvo za osiguranje ili s njim povezana osoba posredno ili neposredno ne posjeduju poslovni udio odnosno druga prava na temelju kojih mogu sudjelovati u pravu glasa odnosno kapitalu društva GrECo JLT Croatia d.o.o. za posredovanje u osiguranju. </xsl:text></fo:inline>
</fo:block>
<fo:block text-align="justify" white-space-collapse="false"  hyphenate="true" language="en"  linefeed-treatment="preserve" white-space-treatment="ignore-if-surrounding-linefeed" >
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="8.0pt">
<xsl:text>
</xsl:text></fo:inline>
</fo:block>
<fo:block text-align="justify" white-space-collapse="false"  hyphenate="true" language="en"  linefeed-treatment="preserve" white-space-treatment="ignore-if-surrounding-linefeed" >
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="8.0pt">
</fo:inline>
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="8.0pt">
<xsl:text>Osiguranici mogu izvansudskim postupkom rješavati sporove sa osigurateljem temeljem obveze društva za osiguranje da uspostavi postupak izvansudskog rješavanja sporova između osiguranika, odnosno ugovaratelja osiguranja, odnosno potrošača i društva za osiguranje, odnosno ponuditelja usluga osiguranja. </xsl:text></fo:inline>
</fo:block>
<fo:block text-align="justify" white-space-collapse="false"  hyphenate="true" language="en"  linefeed-treatment="preserve" white-space-treatment="ignore-if-surrounding-linefeed" >
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="8.0pt">
<xsl:text>
</xsl:text></fo:inline>
</fo:block>
<fo:block text-align="justify" white-space-collapse="false"  hyphenate="true" language="en"  linefeed-treatment="preserve" white-space-treatment="ignore-if-surrounding-linefeed" >
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="8.0pt">
</fo:inline>
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="8.0pt">
<xsl:text>Društvo za osiguranje dužno je u uvjetima osiguranja objaviti informaciju o načinu postupka izvansudskog rješavanja sporova te uspostaviti interni postupak za rješavanje pritužbi osiguranika.</xsl:text></fo:inline>
</fo:block>
<fo:block text-align="justify" white-space-collapse="false"  hyphenate="true" language="en"  linefeed-treatment="preserve" white-space-treatment="ignore-if-surrounding-linefeed" >
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="8.0pt">
</fo:inline>
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="8.0pt">
<xsl:text> 
</xsl:text></fo:inline>
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="8.0pt">
<xsl:text>Osim prethodno navedenog, osiguranici se mogu obratiti Pravobranitelju za područje osiguranja koje djeluje kroz djelatnost Hrvatskog ureda za osiguranje s ciljem rješavanja pritužbi osiguranika odnosno oštećenih osoba. Na čelu Pravobraniteljstva za područje osiguranja je pravobranitelj osiguranja čiji je opseg djelovanja usredotočen isključivo na utvrđivanje kršenja dobrih poslovnih običaja i temeljnih standarda osigurateljne struke. Pravobranitelj dakle odlučuje da li je neko konkretno postupanje društva za osiguranje u suprotnosti sa osnovnim načelima </xsl:text></fo:inline>
<fo:inline color="rgb-icc(0,90,161, #CMYK, 1.0,0.44,0.0,0.37)" font-family="Calibri" font-size="8.0pt">
<xsl:text>Kodeksa poslovne osigurateljne etike i drugih dobrih poslovnih običaja</xsl:text></fo:inline>
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="8.0pt">
<xsl:text> – tog općeobvezujućeg akta koji su društva za osiguranje prihvatila i obvezala se na njegovo poštivanje. </xsl:text></fo:inline>
</fo:block>
<fo:block text-align="justify" white-space-collapse="false"  hyphenate="true" language="en"  linefeed-treatment="preserve" white-space-treatment="ignore-if-surrounding-linefeed" >
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="8.0pt">
<xsl:text>
</xsl:text></fo:inline>
</fo:block>
<fo:block text-align="justify" white-space-collapse="false"  hyphenate="true" language="en"  linefeed-treatment="preserve" white-space-treatment="ignore-if-surrounding-linefeed" >
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="8.0pt">
</fo:inline>
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="8.0pt">
<xsl:text>Svoje pritužbe stranke mogu uputiti pravobranitelju osiguranja u pisanom obliku na adresu Hrvatskog ureda za osiguranje, Zagreb, Martićeva 73 – za pravobranitelja. Pritužba koju nezadovoljna strana upućuje pravobranitelju mora sadržavati podatke o društvu za osiguranje (naziv, adresa i broj predmeta) te zahtjev i činjenice na kojima se temelji kao i dokaze na kojima se te činjenice utvrđuju – te mora biti potpisana. Pritužba mora pravobranitelju osiguranja biti dostavljena u roku od 6 mjeseci od postupka društva za osiguranje za koji stranka smatra da predstavlja kršenje Kodeksa osiguranja. Prije podnošenja pritužbe pravobranitelju osiguranja, stranka se sa svojom pritužbom mora obratiti odgovornom društvu za osiguranje - prethodno odlučivanje u internom žalbenom postupku naime, predstavlja procesnu pretpostavku te pravobranitelj osiguranja neće uzeti u razmatranje pritužbu koja nije prethodno raspravljana u internom žalbenom postupku.</xsl:text></fo:inline>
</fo:block>
</fo:block>
</fo:block-container>
<fo:block break-after="auto"/>
<fo:block text-align="start" color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="12.0pt" padding-bottom="0.0pt" start-indent="0.0pt" end-indent="0.0pt" padding-top="0.0pt" padding="0.0pt" display-align="before" position="relative" height="21.0pt" width="140.0pt" keep-together="auto"  line-height="13.2pt" white-space-collapse="false"  linefeed-treatment="preserve" white-space-treatment="ignore-if-surrounding-linefeed"  hyphenate="false" language="en" ><fo:block id="LastPage" line-height="0" keep-with-previous="always"/></fo:block>
<xsl:if test='position()=last()'>
  <fo:block id="lastPage"/>
</xsl:if>
</fo:flow>
</fo:page-sequence>
</fo:root>
</xsl:template>

<!-- GENERATED TEMPLATE templ_header -->
<xsl:template name="templ_header" >
<fo:block-container absolute-position="absolute" left="1.41cm" top="2.2cm" width="12.0cm" height="0.53" > 
 		<fo:block display-align="before" text-align="start" font-family="Calibri" font-size="9.0pt" font-weight="bold">
			<xsl:text>GrECo JLT Croatia d.o.o.</xsl:text>
		</fo:block>
</fo:block-container>

<fo:block-container absolute-position="absolute" left="1.41cm" top="2.5cm" width="12.0cm" height="0.53" > 
	<fo:block display-align="before" text-align="start" font-family="Calibri" font-size="8.0pt" >
		<xsl:text>za posredovanje u osiguranju</xsl:text>
	</fo:block>
</fo:block-container>
	
<fo:block-container absolute-position="absolute" top="0.0pt" right="0.9cm" width="128.0pt" height="50.0pt"> <!-- left="150.0pt" -->
	<fo:block span="none" text-align="right">
		<!-- <fo:external-graphic src="{$filename}" height="31.0pt"/> -->
	<fo:external-graphic src="url({concat($common_img,'GrECo_Logo.jpg')})"/>
</fo:block>
</fo:block-container>
</xsl:template>

<!-- GENERATED TEMPLATE templ_header_logo_only -->
<xsl:template name="templ_header_logo_only" >
<fo:block-container absolute-position="absolute" top="0.0pt" right="0.9cm" width="128.0pt" height="50.0pt"> <!-- left="150.0pt" -->
	<fo:block span="none" text-align="right">
		<fo:external-graphic src="url({concat($common_img,'GrECo_Logo.jpg')})"/>
	</fo:block>
</fo:block-container>
				</xsl:template>

<!-- GENERATED TEMPLATE templ_footer -->
<xsl:template name="templ_footer" >
<fo:block-container absolute-position="absolute" top="0.0cm" right="0.0cm" > <!-- left="150.0pt" -->
	<fo:block text-align="start">
        	<fo:leader leader-pattern="rule"
                   rule-thickness="0.1pt"
                   leader-length="18.8cm"
                   start-indent="0cm"
                   end-indent="0cm"
                   color="black"/>
      </fo:block>
</fo:block-container>

<xsl:call-template name="table_footer" />

<xsl:call-template name="table_fusszeile" /></xsl:template>

<!-- GENERATED TEMPLATE templ_kopf -->
<xsl:template name="templ_kopf" >
<xsl:param name="kopf_typ" select="default"/>
<fo:block break-before="auto"/>
<fo:block-container  reference-orientation="0" >
<fo:block space-after="12.0pt" space-after.conditionality="retain" keep-together="auto" ><!-- GENERATE TABLE START-->

<fo:table table-layout="fixed" width="100%">
<fo:table-column column-width="469.0pt" />
<fo:table-body>
<xsl:for-each select=".">

    <fo:table-row>
    <fo:table-cell>
         <fo:block/>
    </fo:table-cell>

    </fo:table-row>

    <fo:table-row>
<fo:table-cell padding-bottom="0.0pt" start-indent="0.0pt" end-indent="0.0pt" padding-top="0.0pt" padding="0.0pt" display-align="before" width="469.0pt"  reference-orientation="0">
<fo:block break-before="auto"/>
<fo:block-container  reference-orientation="0" >
<fo:block space-after="24.0pt" space-after.conditionality="retain" space-before="10.0pt" space-before.conditionality="retain" keep-together="auto" ><!-- GENERATE TABLE START-->

<fo:table table-layout="fixed" width="100%">
<fo:table-column column-width="261.0pt" />
<fo:table-column column-width="208.0pt" />
<fo:table-body>
<xsl:for-each select=".">

    <fo:table-row>
    <fo:table-cell>
         <fo:block/>
    </fo:table-cell>
<fo:table-cell padding-bottom="0.0pt" start-indent="0.0pt" end-indent="0.0pt" padding-top="0.0pt" padding="0.0pt" display-align="before" width="208.0pt"  reference-orientation="0">
<fo:block break-before="auto"/>
<fo:block-container  reference-orientation="0" >
<fo:block keep-together="auto" ><!-- GENERATE TABLE START-->

<fo:table table-layout="fixed" width="100%">
<fo:table-column column-width="208.0pt" />
<fo:table-body>
<xsl:for-each select=".">

    <fo:table-row>
<fo:table-cell padding-bottom="0.0pt" start-indent="0.0pt" end-indent="0.0pt" padding-top="0.0pt" padding="0.0pt" display-align="before" width="208.0pt"  reference-orientation="0">
<fo:block-container display-align="before" reference-orientation="0">
<fo:block position="relative" text-align="end" color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="8.0pt" white-space-collapse="false"  linefeed-treatment="preserve" white-space-treatment="ignore-if-surrounding-linefeed"  hyphenate="false" language="en"  padding-bottom="0.0pt" start-indent="0.0pt" end-indent="0.0pt" padding-top="0.0pt" padding="0.0pt"><fo:block font-family="Calibri" font-size="8pt">
<xsl:text>Zelinska 3, HR-10000 Zagreb</xsl:text>
</fo:block></fo:block>
</fo:block-container>
</fo:table-cell>

    </fo:table-row>

    <fo:table-row>
<fo:table-cell padding-bottom="0.0pt" start-indent="0.0pt" end-indent="0.0pt" padding-top="0.0pt" padding="0.0pt" display-align="before" width="208.0pt"  reference-orientation="0">
<fo:block-container display-align="before" reference-orientation="0">
<fo:block position="relative" text-align="end" color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="8.0pt" white-space-collapse="false"  linefeed-treatment="preserve" white-space-treatment="ignore-if-surrounding-linefeed"  hyphenate="false" language="en"  padding-bottom="0.0pt" start-indent="0.0pt" end-indent="0.0pt" padding-top="0.0pt" padding="0.0pt"><xsl:text>Hrvatska</xsl:text></fo:block>
</fo:block-container>
</fo:table-cell>

    </fo:table-row>

    <fo:table-row>
<fo:table-cell padding-bottom="0.0pt" start-indent="0.0pt" end-indent="0.0pt" padding-top="0.0pt" padding="0.0pt" display-align="before" width="208.0pt"  reference-orientation="0">
<fo:block-container display-align="before" reference-orientation="0">
<fo:block position="relative" text-align="end" color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="8.0pt" white-space-collapse="false"  linefeed-treatment="preserve" white-space-treatment="ignore-if-surrounding-linefeed"  hyphenate="false" language="en"  padding-bottom="0.0pt" start-indent="0.0pt" end-indent="0.0pt" padding-top="0.0pt" padding="0.0pt"><xsl:text>Tel.: +385 (1) 668 1 633</xsl:text></fo:block>
</fo:block-container>
</fo:table-cell>

    </fo:table-row>

    <fo:table-row>
    <fo:table-cell>
         <fo:block/>
    </fo:table-cell>

    </fo:table-row>

    <fo:table-row>
<fo:table-cell padding-bottom="0.0pt" start-indent="0.0pt" end-indent="0.0pt" padding-top="0.0pt" padding="0.0pt" display-align="before" width="208.0pt"  reference-orientation="0">
<fo:block-container display-align="before" reference-orientation="0">
<fo:block position="relative" text-align="end" color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="8.0pt" white-space-collapse="false"  linefeed-treatment="preserve" white-space-treatment="ignore-if-surrounding-linefeed"  hyphenate="false" language="en"  padding-bottom="0.0pt" start-indent="0.0pt" end-indent="0.0pt" padding-top="0.0pt" padding="0.0pt"><xsl:text>Fax: + 385 (1) 6111 - 749</xsl:text></fo:block>
</fo:block-container>
</fo:table-cell>

    </fo:table-row>

    <fo:table-row>
<fo:table-cell padding-bottom="0.0pt" start-indent="0.0pt" end-indent="0.0pt" padding-top="0.0pt" padding="0.0pt" display-align="before" width="208.0pt"  reference-orientation="0">
<fo:block-container display-align="before" reference-orientation="0">
<fo:block position="relative" text-align="end" color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="8.0pt" white-space-collapse="false"  linefeed-treatment="preserve" white-space-treatment="ignore-if-surrounding-linefeed"  hyphenate="false" language="en"  padding-bottom="0.0pt" start-indent="0.0pt" end-indent="0.0pt" padding-top="0.0pt" padding="0.0pt"><xsl:text>E-Mail: prodaja@greco.hr</xsl:text></fo:block>
</fo:block-container>
</fo:table-cell>

    </fo:table-row>

    <fo:table-row>
<fo:table-cell padding-bottom="0.0pt" start-indent="0.0pt" end-indent="0.0pt" padding-top="0.0pt" padding="0.0pt" display-align="before" width="208.0pt"  reference-orientation="0">
<fo:block-container display-align="before" reference-orientation="0">
<fo:block position="relative" text-align="end" color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="8.0pt" white-space-collapse="false"  linefeed-treatment="preserve" white-space-treatment="ignore-if-surrounding-linefeed"  hyphenate="false" language="en"  padding-bottom="4.0pt" start-indent="0.0pt" end-indent="0.0pt" padding-top="0.0pt"><xsl:text>www.greco-jlt.com</xsl:text></fo:block>
</fo:block-container>
</fo:table-cell>

    </fo:table-row>

    <fo:table-row>
<fo:table-cell padding-bottom="0.0pt" start-indent="0.0pt" end-indent="0.0pt" padding-top="0.0pt" padding="0.0pt" display-align="before" width="208.0pt"  reference-orientation="0">
<fo:block-container display-align="before" reference-orientation="0">
<fo:block position="relative" text-align="end" color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="8.0pt" white-space-collapse="false"  linefeed-treatment="preserve" white-space-treatment="ignore-if-surrounding-linefeed"  hyphenate="false" language="en"  padding-bottom="0.0pt" start-indent="0.0pt" end-indent="0.0pt" padding-top="0.0pt" padding="0.0pt"><xsl:text>Erste u. Steiermärkische Bank d.d., Zagreb, TR - HRK: 2402006-1100613671</xsl:text></fo:block>
</fo:block-container>
</fo:table-cell>

    </fo:table-row>

    <fo:table-row>
<fo:table-cell padding-bottom="0.0pt" start-indent="0.0pt" end-indent="0.0pt" padding-top="0.0pt" padding="0.0pt" display-align="before" width="208.0pt"  reference-orientation="0">
<fo:block-container display-align="before" reference-orientation="0">
<fo:block position="relative" text-align="end" color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="8.0pt" white-space-collapse="false"  linefeed-treatment="preserve" white-space-treatment="ignore-if-surrounding-linefeed"  hyphenate="false" language="en"  padding-bottom="0.0pt" start-indent="0.0pt" end-indent="0.0pt" padding-top="0.0pt" padding="0.0pt"><xsl:text>TR - devizna plaćanja: IBAN: HR(1424020061100613671)</xsl:text></fo:block>
</fo:block-container>
</fo:table-cell>

    </fo:table-row>

    <fo:table-row>
<fo:table-cell padding-bottom="0.0pt" start-indent="0.0pt" end-indent="0.0pt" padding-top="0.0pt" padding="0.0pt" display-align="before" width="208.0pt"  reference-orientation="0">
<fo:block-container display-align="before" reference-orientation="0">
<fo:block position="relative" text-align="end" color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="8.0pt" white-space-collapse="false"  linefeed-treatment="preserve" white-space-treatment="ignore-if-surrounding-linefeed"  hyphenate="false" language="en"  padding-bottom="0.0pt" start-indent="0.0pt" end-indent="0.0pt" padding-top="0.0pt" padding="0.0pt"><xsl:text>Trgovački sud Zagreb, MBS: 080012200</xsl:text></fo:block>
</fo:block-container>
</fo:table-cell>

    </fo:table-row>

    <fo:table-row>
<fo:table-cell padding-bottom="0.0pt" start-indent="0.0pt" end-indent="0.0pt" padding-top="0.0pt" padding="0.0pt" display-align="before" width="208.0pt"  reference-orientation="0">
<fo:block-container display-align="before" reference-orientation="0">
<fo:block position="relative" text-align="end" color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="8.0pt" white-space-collapse="false"  linefeed-treatment="preserve" white-space-treatment="ignore-if-surrounding-linefeed"  hyphenate="false" language="en"  padding-bottom="0.0pt" start-indent="0.0pt" end-indent="0.0pt" padding-top="0.0pt" padding="0.0pt"><xsl:text>OIB: 38928475156</xsl:text></fo:block>
</fo:block-container>
</fo:table-cell>

    </fo:table-row>

    <fo:table-row>
<fo:table-cell padding-bottom="0.0pt" start-indent="0.0pt" end-indent="0.0pt" padding-top="0.0pt" padding="0.0pt" display-align="before" width="208.0pt"  reference-orientation="0">
<fo:block-container display-align="before" reference-orientation="0">
<fo:block position="relative" text-align="end" color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="8.0pt" white-space-collapse="false"  linefeed-treatment="preserve" white-space-treatment="ignore-if-surrounding-linefeed"  hyphenate="false" language="en"  padding-bottom="0.0pt" start-indent="0.0pt" end-indent="0.0pt" padding-top="0.0pt" padding="0.0pt"><xsl:text>Dozvola HANFE od 11.01.2007.</xsl:text></fo:block>
</fo:block-container>
</fo:table-cell>

    </fo:table-row>

    <fo:table-row>
<fo:table-cell padding-bottom="0.0pt" start-indent="0.0pt" end-indent="0.0pt" padding-top="0.0pt" padding="0.0pt" display-align="before" width="208.0pt"  reference-orientation="0">
<fo:block-container display-align="before" reference-orientation="0">
<fo:block position="relative" text-align="end" color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="8.0pt" white-space-collapse="false"  linefeed-treatment="preserve" white-space-treatment="ignore-if-surrounding-linefeed"  hyphenate="false" language="en"  padding-bottom="0.0pt" start-indent="0.0pt" end-indent="0.0pt" padding-top="0.0pt" padding="0.0pt"><xsl:text>Šifra djelatnosti: 67200</xsl:text></fo:block>
</fo:block-container>
</fo:table-cell>

    </fo:table-row>
</xsl:for-each></fo:table-body>
</fo:table>
</fo:block></fo:block-container>
<fo:block break-after="auto"/>
</fo:table-cell>

    </fo:table-row>
</xsl:for-each></fo:table-body>
</fo:table>
</fo:block></fo:block-container>
<fo:block break-after="auto"/>
</fo:table-cell>

    </fo:table-row>

    <fo:table-row>
<fo:table-cell padding-bottom="0.0pt" start-indent="0.0pt" end-indent="0.0pt" padding-top="0.0pt" padding="0.0pt" display-align="before" width="469.0pt"  reference-orientation="0">
<fo:block break-before="auto"/>
<fo:block-container  reference-orientation="0" >
<fo:block space-before="10.0pt" space-before.conditionality="retain" keep-together="auto" ><!-- GENERATE TABLE START-->

<fo:table table-layout="fixed" width="100%">
<fo:table-column column-width="261.0pt" />
<fo:table-column column-width="208.0pt" />
<fo:table-body>
<xsl:for-each select=".">

    <fo:table-row>
    <fo:table-cell>
         <fo:block/>
    </fo:table-cell>
<fo:table-cell padding-bottom="0.0pt" start-indent="0.0pt" end-indent="0.0pt" padding-top="0.0pt" padding="0.0pt" display-align="before" width="208.0pt"  reference-orientation="0">
<fo:block-container display-align="before" reference-orientation="0">
<fo:block position="relative" text-align="end" color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="11.0pt" white-space-collapse="false"  linefeed-treatment="preserve" white-space-treatment="ignore-if-surrounding-linefeed"  hyphenate="false" language="en"  padding-bottom="0.0pt" start-indent="0.0pt" end-indent="0.0pt" padding-top="0.0pt" padding="0.0pt"><xsl:text>Zagreb, </xsl:text>
<xsl:value-of select="format-date(current-date(), '[D01].[M01].[Y0001]')" /></fo:block>
</fo:block-container>
</fo:table-cell>

    </fo:table-row>
</xsl:for-each></fo:table-body>
</fo:table>
</fo:block></fo:block-container>
<fo:block break-after="auto"/>
</fo:table-cell>

    </fo:table-row>
</xsl:for-each></fo:table-body>
</fo:table>
</fo:block></fo:block-container>
<fo:block break-after="auto"/>
</xsl:template>

<!-- GENERATED TEMPLATE table_footer -->
<xsl:template name="table_footer" >
<fo:block break-before="auto"/>
<fo:block-container  reference-orientation="0" >
<fo:block keep-together="auto" ><!-- GENERATE TABLE START-->

<fo:table table-layout="fixed" width="100%">
<fo:table-column column-width="85.36pt" />
<fo:table-column column-width="446.71pt" />
<fo:table-body>
<xsl:for-each select=".">

    <fo:table-row>
<fo:table-cell padding-bottom="0.0pt" start-indent="0.0pt" end-indent="0.0pt" padding-top="0.0pt" padding="0.0pt" display-align="before" width="85.36pt"  reference-orientation="0">
<fo:block-container display-align="before" reference-orientation="0">
<fo:block position="relative" text-align="start" color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="11.0pt" white-space-collapse="false"  linefeed-treatment="preserve" white-space-treatment="ignore-if-surrounding-linefeed"  hyphenate="true" language="en"  padding-bottom="0.0pt" start-indent="0.0pt" end-indent="0.0pt" padding-top="0.0pt" padding="0.0pt"><fo:block-container absolute-position="absolute" top="0.5cm" left="0.0cm" width="128.0pt" height="30.0pt"> <!-- left="150.0pt" -->
		<fo:block span="none" text-align="left">
			<fo:external-graphic src="url({concat($common_img,'JLT_Partner_Footer.jpg')})" height="31.0pt"/>
		</fo:block>
</fo:block-container>
</fo:block>
</fo:block-container>
</fo:table-cell>
<fo:table-cell padding-bottom="0.0pt" start-indent="0.0pt" end-indent="0.0pt" padding-top="0.0pt" padding="0.0pt" display-align="before" width="446.71pt"  reference-orientation="0">
<fo:block-container display-align="before" reference-orientation="0">
<fo:block position="relative" text-align="start" color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Arial" font-size="12.0pt" white-space-collapse="false"  linefeed-treatment="preserve" white-space-treatment="ignore-if-surrounding-linefeed"  hyphenate="true" language="en"  padding-bottom="0.0pt" start-indent="0.0pt" end-indent="0.0pt" padding-top="0.0pt" padding="0.0pt"><xsl:call-template name="Standorte"></xsl:call-template></fo:block>
</fo:block-container>
</fo:table-cell>

    </fo:table-row>
</xsl:for-each></fo:table-body>
</fo:table>
</fo:block></fo:block-container>
<fo:block break-after="auto"/>
</xsl:template>

<!-- GENERATED TEMPLATE Standorte -->
<xsl:template name="Standorte" >
<fo:block break-before="auto"/>
<fo:block-container  reference-orientation="0" >
<fo:block keep-together="auto" ><!-- GENERATE TABLE START-->

<fo:table table-layout="fixed" width="100%">
<fo:table-column column-width="446.71pt" />
<fo:table-body>
<xsl:for-each select=".">

    <fo:table-row>
<fo:table-cell padding-bottom="0.0pt" start-indent="0.0pt" end-indent="0.0pt" padding-top="0.0pt" padding="0.0pt" display-align="before" width="446.71pt"  reference-orientation="0">
<fo:block-container display-align="before" reference-orientation="0">
<fo:block position="relative" text-align="start" color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="11.0pt" white-space-collapse="false"  linefeed-treatment="preserve" white-space-treatment="ignore-if-surrounding-linefeed"  hyphenate="true" language="en"  padding-bottom="0.0pt" start-indent="0.0pt" end-indent="0.0pt" padding-top="0.0pt" padding="0.0pt"><fo:block-container absolute-position="absolute" top="1.0cm" right="0.0cm" > <!-- left="150.0pt" -->
	<fo:block span="none" text-align="right" font-family="Calibri" font-size="6.5pt">
		<xsl:text>Austria</xsl:text>
		<fo:inline font-weight="bold"><xsl:text> &#xB7; </xsl:text></fo:inline>
		<xsl:text>Bulgaria</xsl:text>
		<fo:inline font-weight="bold"><xsl:text> &#xB7; </xsl:text></fo:inline>
		<xsl:text>Croatia</xsl:text>
		<fo:inline font-weight="bold"><xsl:text> &#xB7; </xsl:text></fo:inline>
		<xsl:text>Czech Republic</xsl:text>
		<fo:inline font-weight="bold"><xsl:text> &#xB7; </xsl:text></fo:inline>
		<xsl:text>Estonia</xsl:text>
		<fo:inline font-weight="bold"><xsl:text> &#xB7; </xsl:text></fo:inline>
	 	<xsl:text>Hungary</xsl:text>
		<fo:inline font-weight="bold"><xsl:text> &#xB7; </xsl:text></fo:inline>
	 	<xsl:text>Kazakhstan</xsl:text>
		<fo:inline font-weight="bold"><xsl:text> &#xB7; </xsl:text></fo:inline>
	 	<xsl:text>Lithuania</xsl:text>
		<fo:inline font-weight="bold"><xsl:text> &#xB7; </xsl:text></fo:inline>
		<xsl:text>Poland</xsl:text>
		<fo:inline font-weight="bold"><xsl:text> &#xB7; </xsl:text></fo:inline>
		<xsl:text>Romania</xsl:text>
		<fo:inline font-weight="bold"><xsl:text> &#xB7; </xsl:text></fo:inline>		
		<xsl:text>Russia</xsl:text>
		<fo:inline font-weight="bold"><xsl:text> &#xB7; </xsl:text></fo:inline>		
		<xsl:text>Serbia</xsl:text>
		<fo:inline font-weight="bold"><xsl:text> &#xB7; </xsl:text></fo:inline>
		<xsl:text>Slovakia</xsl:text>
		<fo:inline font-weight="bold"><xsl:text> &#xB7; </xsl:text></fo:inline>		
		<xsl:text>Slovenia</xsl:text>
		<fo:inline font-weight="bold"><xsl:text> &#xB7; </xsl:text></fo:inline>		
		<xsl:text>Turkey</xsl:text>
		<fo:inline font-weight="bold"><xsl:text> &#xB7; </xsl:text></fo:inline>		
		<xsl:text>Ukraine</xsl:text>
		<fo:inline font-weight="bold"></fo:inline>
	</fo:block>
</fo:block-container>
</fo:block>
</fo:block-container>
</fo:table-cell>

    </fo:table-row>

    <fo:table-row>
    <fo:table-cell>
         <fo:block/>
    </fo:table-cell>

    </fo:table-row>
</xsl:for-each></fo:table-body>
</fo:table>
</fo:block></fo:block-container>
<fo:block break-after="auto"/>
</xsl:template>

<!-- GENERATED TEMPLATE table_fusszeile -->
<xsl:template name="table_fusszeile" >
<fo:block break-before="auto"/>
<fo:block space-before="22.76pt" space-before.conditionality="retain" keep-together="auto" ><!-- GENERATE TABLE START-->

<fo:table table-layout="fixed" width="100%">
<fo:table-column column-width="240.0pt" />
<fo:table-column column-width="190.0pt" />
<fo:table-column column-width="106.0pt" />
<fo:table-body>
<xsl:for-each select=".">

    <fo:table-row>
<fo:table-cell padding-bottom="0.0pt" start-indent="0.0pt" end-indent="0.0pt" padding-top="0.0pt" padding="0.0pt" display-align="before" width="240.0pt"  reference-orientation="0">
<fo:block position="relative" white-space-collapse="false"  linefeed-treatment="preserve"  start-indent="2.0pt" display-align="before" text-align="start" color="#666666" font-family="Calibri" font-size="7.0pt">
	<xsl:text>&#xA0;</xsl:text>
</fo:block>
<fo:block/>
</fo:table-cell>
    <fo:table-cell>
         <fo:block/>
    </fo:table-cell>
<fo:table-cell padding-bottom="0.0pt" start-indent="0.0pt" end-indent="0.0pt" padding-top="0.0pt" padding="0.0pt" display-align="before" width="106.0pt"  reference-orientation="0">
<fo:block-container display-align="before" reference-orientation="0">
<fo:block position="relative" white-space-collapse="false"  linefeed-treatment="preserve" display-align="before" text-align="end" color="#666666" font-family="Calibri" font-size="7.0pt">
	<xsl:text>&#xA0;</xsl:text>
</fo:block></fo:block-container>
</fo:table-cell>

    </fo:table-row>

    <fo:table-row>
<fo:table-cell padding-bottom="0.0pt" start-indent="0.0pt" end-indent="0.0pt" padding-top="0.0pt" padding="0.0pt" display-align="before" width="240.0pt"  reference-orientation="0">
<fo:block position="relative" white-space-collapse="false"  linefeed-treatment="preserve"  start-indent="2.0pt" display-align="before" text-align="start" color="#666666" font-family="Calibri" font-size="7.0pt">
	<xsl:text>&#xA0;</xsl:text>
</fo:block>
<fo:block/>
</fo:table-cell>
    <fo:table-cell>
         <fo:block/>
    </fo:table-cell>
<fo:table-cell padding-bottom="0.0pt" start-indent="0.0pt" end-indent="0.0pt" padding-top="0.0pt" padding="0.0pt" display-align="before" width="106.0pt"  reference-orientation="0">
<fo:block-container display-align="before" reference-orientation="0">
<fo:block position="relative" white-space-collapse="false"  linefeed-treatment="preserve" display-align="before" text-align="end" color="#666666" font-family="Calibri" font-size="7.0pt">
	<xsl:text>&#xA0;</xsl:text>
</fo:block></fo:block-container>
</fo:table-cell>

    </fo:table-row>

    <fo:table-row>
<fo:table-cell padding-bottom="0.0pt" start-indent="0.0pt" end-indent="0.0pt" padding-top="0.0pt" padding="0.0pt" display-align="before" width="240.0pt"  reference-orientation="0">
<fo:block-container absolute-position="absolute" top="0.4cm" left="0.0cm" > 
	<fo:block start-indent="2.0pt" display-align="before" text-align="start" color="#666666" font-family="Calibri" font-size="7.0pt">
		<xsl:text>ID </xsl:text>
		<xsl:value-of select="format-date(current-date(), '[Y0001][M01][D01]')" />
		<xsl:value-of select="concat('/',NS1:item[@NS1:name='user_uid']/@NS1:value)"/>
	</fo:block>
</fo:block-container><fo:block/>
</fo:table-cell>
    <fo:table-cell>
         <fo:block/>
    </fo:table-cell>
<fo:table-cell padding-bottom="0.0pt" start-indent="0.0pt" end-indent="0.0pt" padding-top="0.0pt" padding="0.0pt" display-align="before" width="106.0pt"  reference-orientation="0">
<fo:block-container display-align="before" reference-orientation="0">
<fo:block-container absolute-position="absolute" top="0.4cm" right="0.0cm" >         
	<fo:block position="relative" white-space-collapse="false"  linefeed-treatment="preserve" display-align="before" text-align="end" color="#666666" font-family="Calibri" font-size="7.0pt">
		<xsl:value-of select="concat('Stranica', ' ')"/>
		<fo:page-number/>
		<xsl:value-of select="concat(' ', 'od', ' ')"/>
		<fo:page-number-citation ref-id="LastPage"/>
	</fo:block>
</fo:block-container>
</fo:block-container>
</fo:table-cell>

    </fo:table-row>
</xsl:for-each></fo:table-body>
</fo:table>
</fo:block><fo:block break-after="auto"/>
</xsl:template>

<!-- GENERATED TEMPLATE table_fuss_freitext -->
<xsl:template name="table_fuss_freitext" >
<fo:block break-before="auto"/>
<fo:block-container  reference-orientation="0" >
<fo:block keep-together="auto" ><!-- GENERATE TABLE START-->

<fo:table table-layout="fixed" width="100%">
<fo:table-column column-width="235.0pt" />
<fo:table-column column-width="234.0pt" />
<fo:table-body>
<xsl:for-each select=".">

    <fo:table-row>
<fo:table-cell padding-bottom="0.0pt" start-indent="0.0pt" end-indent="0.0pt" padding-top="0.0pt" padding="0.0pt" number-columns-spanned="2" display-align="before" width="235.0pt"  reference-orientation="0">
<fo:block-container display-align="before" reference-orientation="0">
<fo:block position="relative" text-align="start" color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="11.0pt" white-space-collapse="false"  linefeed-treatment="preserve" white-space-treatment="ignore-if-surrounding-linefeed"  hyphenate="false" language="en"  padding-bottom="0.0pt" start-indent="0.0pt" end-indent="0.0pt" padding-top="0.0pt" padding="0.0pt"><xsl:text>&#xA0;</xsl:text></fo:block>
</fo:block-container>
</fo:table-cell>

    </fo:table-row>

    <fo:table-row keep-with-next="always">
<fo:table-cell padding-bottom="0.0pt" start-indent="0.0pt" end-indent="0.0pt" padding-top="0.0pt" padding="0.0pt" number-columns-spanned="2" display-align="before" width="235.0pt"  reference-orientation="0">
<fo:block-container display-align="before" reference-orientation="0">
<fo:block position="relative" text-align="start" color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="11.0pt" white-space-collapse="false"  linefeed-treatment="preserve" white-space-treatment="ignore-if-surrounding-linefeed"  hyphenate="false" language="en"  padding-bottom="0.0pt" start-indent="0.0pt" end-indent="0.0pt" padding-top="0.0pt" padding="0.0pt"><xsl:text>Srdačan pozdrav</xsl:text></fo:block>
</fo:block-container>
</fo:table-cell>

    </fo:table-row>

    <fo:table-row keep-with-next="always" keep-with-previous="always">
<fo:table-cell padding-bottom="0.0pt" start-indent="0.0pt" end-indent="0.0pt" padding-top="0.0pt" padding="0.0pt" number-columns-spanned="2" display-align="before" width="235.0pt"  reference-orientation="0">
<fo:block-container display-align="before" reference-orientation="0">
<fo:block position="relative" text-align="start" color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="11.0pt" white-space-collapse="false"  linefeed-treatment="preserve" white-space-treatment="ignore-if-surrounding-linefeed"  hyphenate="false" language="en"  padding-bottom="0.0pt" start-indent="0.0pt" end-indent="0.0pt" padding-top="10.0pt"><xsl:text>GrECo JLT Croatia d.o.o.</xsl:text></fo:block>
</fo:block-container>
</fo:table-cell>

    </fo:table-row>
</xsl:for-each></fo:table-body>
</fo:table>
</fo:block></fo:block-container>
<fo:block break-after="auto"/>
</xsl:template>

<!-- GENERATED TEMPLATE check_invalid -->
<xsl:template name="check_invalid" >
<fo:block-container display-align="before" reference-orientation="0" fox:transform="rotate(0) , translate(0, 0)">
<fo:block text-align="start" color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Arial" font-size="12.0pt" padding-bottom="0.0pt" start-indent="0.0pt" end-indent="0.0pt" padding-top="0.0pt" padding="0.0pt" position="relative" height="73.0pt" width="754.0pt" keep-together="auto"  line-height="14.5pt" white-space-collapse="false"  linefeed-treatment="preserve" white-space-treatment="ignore-if-surrounding-linefeed"  hyphenate="true" language="en" ><xsl:variable name="check_new_car">
	<xsl:choose>

	<xsl:when test="NS1:item[@NS1:name='new_car']/@NS1:value='Yes' or NS1:item[@NS1:name='new_car']/@NS1:value='No'">
	<xsl:text>OK</xsl:text>
	</xsl:when>
	
	<xsl:otherwise> 
	<xsl:text>NOK</xsl:text>
	</xsl:otherwise>
	
	</xsl:choose>
</xsl:variable>


<xsl:variable name="check_finance_type">
	<xsl:choose>

	<xsl:when test="NS1:item[@NS1:name='finance_type']/@NS1:value='OL' or NS1:item[@NS1:name='finance_type']/@NS1:value='FL'" >
	<xsl:text>OK</xsl:text>
	</xsl:when>
	
	<xsl:otherwise> 
	<xsl:text>NOK</xsl:text>
	</xsl:otherwise>
	
	</xsl:choose>
</xsl:variable>


<xsl:variable name="check_finance_amount_string">
	<xsl:choose>

	<xsl:when test="NS1:item[@NS1:name='finance_amount_string']/@NS1:value!='' and NS1:item[@NS1:name='finance_amount_string']/@NS1:value!='INVALID'" >
	<xsl:text>OK</xsl:text>
	</xsl:when>
	
	<xsl:otherwise> 
	<xsl:text>NOK</xsl:text>
	</xsl:otherwise>
	
	</xsl:choose>
</xsl:variable>


<xsl:variable name="check_premium_uniqa_wstv_string">
	<xsl:choose>

	<xsl:when test="NS1:item[@NS1:name='premium_uniqa_string']/@NS1:value!='' and NS1:item[@NS1:name='premium_wstv_string']/@NS1:value!='' and NS1:item[@NS1:name='premium_uniqa_string']/@NS1:value!='INVALID' and NS1:item[@NS1:name='premium_wstv_string']/@NS1:value!='INVALID'" >
	<xsl:text>OK</xsl:text>
	</xsl:when>
	
	<xsl:otherwise> 
	<xsl:text>NOK</xsl:text>
	</xsl:otherwise>
	
	</xsl:choose>
</xsl:variable>


<xsl:variable name="check_total">
<xsl:value-of select="concat($check_new_car,$check_finance_type,$check_finance_amount_string,$check_premium_uniqa_wstv_string)" />
</xsl:variable>


<fo:block font-size="60pt" font-family="Calibri" color="red">
<xsl:choose>
	<xsl:when test="$check_total!='OKOKOKOK'" >
	<xsl:text>INVALID DATA</xsl:text>
	</xsl:when>

	<xsl:otherwise> 
	<xsl:text></xsl:text>
	</xsl:otherwise>
</xsl:choose>
</fo:block>
</fo:block>
</fo:block-container>
</xsl:template>
<xsl:template match="include-xsl-fo">
    <xsl:copy-of select="@*"/>
</xsl:template>
</xsl:stylesheet>
